#! /usr/bin/bash

mkdir build
cd build

cmake -DKFR_ENABLE_CAPI_BUILD=TRUE -DKFR_ENABLE_MULTIARCH=ON \
      -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_CXX_COMPILER=clang++ -DKFR_WITH_CLANG=OFF -DCMAKE_INSTALL_PREFIX=$PREFIX ..

make -j$(nproc)
make install
