{% set versions = {
    "6.3.1": "800f8e782fb514176c06526792ec766b718a7b91c73e9d07efe47dff6cb0816d",
    "6.2.0": "bc9507e1dde17a86b68fb045404b66c5c486e61e324d9209468ea1e6cac7173c",
    "5.2.0": "8597b7334cf9f317daeeb64615d562a1374545e8c196b06a86705c7a391c6761"
} %}

{% set version = environ.get('ANACONDA_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "kfrlib")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "https://github.com/kfrlib/kfr/archive/refs/tags/{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - clang
    - cmake
    - make
  host:
    - clang

about:
  home: "https://www.kfrlib.com"
  license: "GPLv2"
  summary: "Fast, modern C++ DSP framework, FFT, Sample Rate Conversion, FIR/IIR/Biquad Filters (SSE, AVX, AVX-512, ARM NEON)"
  description: |
    KFR is an open source C++ DSP framework that contains high performance building blocks for DSP, audio, scientific and other applications. It is distributed under dual GPLv2/v3 and commercial license.

extra:
  recipe-maintainers:
    - meiyasan
